title: P.M.Conception Design
description: Pierre Margerie - Dessinateur CAO en bâtiments
url: https://pmc-design.github.io

sass:
  style: compact # possible values: nested expanded compact compressed
  
